{"name": "User re-registration", "status": "passed", "description": "User registration with existing data, expected error", "start": 1705960203067, "stop": 1705960203295, "uuid": "566b5074-b3d0-41d0-8d30-398833b03bd3", "historyId": "afae7fc770ad1ec1bdd4d61270fd36aa", "testCaseId": "afae7fc770ad1ec1bdd4d61270fd36aa", "fullName": "tests.test_create_user.TestCreateUser#test_create_user_duplication_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_user"}, {"name": "subSuite", "value": "TestCreateUser"}, {"name": "host", "value": "DESKTOP-N69F3B6"}, {"name": "thread", "value": "11152-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_user"}]}